# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=250)),
                ('branch_location', models.CharField(max_length=100)),
                ('available_time', models.DateTimeField()),
            ],
        ),
    ]
