# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20170507_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='end_time',
            field=models.DateTimeField(default='2016-01-01T10:20:05.123'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_time',
            field=models.DateTimeField(default='2016-01-01T10:20:05.123'),
        ),
    ]
