# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20170507_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='end_time',
            field=models.DateTimeField(default=datetime.date(2010, 5, 24)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_time',
            field=models.DateTimeField(default=datetime.date(2010, 5, 24)),
        ),
    ]
