# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 07:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20170507_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 1, 34, 31, 371000)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 1, 34, 31, 371000)),
        ),
    ]
