# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 11:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20170507_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 5, 25, 59, 254000)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 5, 25, 59, 254000)),
        ),
    ]
